In [3]:
import numpy as np

In [4]:
a1 = np.array([1,2,3])

In [5]:
a1

array([1, 2, 3])

In [6]:
type(a1)

numpy.ndarray

In [7]:
a2 = np.array([[1, 2.0, 3.3],
             [4, 5, 6]0 ])

In [8]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6. ]])

In [9]:
a3 = np.array([[[3,5,6.6],
               [5,7,8.9],
               [9,2,7.9]]])

In [10]:
a3

array([[[3. , 5. , 6.6],
        [5. , 7. , 8.9],
        [9. , 2. , 7.9]]])

In [11]:
a1.shape

(3,)

In [12]:
a2.shape

(2, 3)

In [13]:
a3.shape

(1, 3, 3)

In [14]:
a1.dtype, a2.dtype

(dtype('int32'), dtype('float64'))

In [15]:
a1.size, a2.size, a3.size

(3, 6, 9)

In [16]:
import pandas as pd

In [17]:
df = pd.DataFrame(a2)

In [18]:
df

0    1    2
0  1.0  2.0  3.3
1  4.0  5.0  6.0

In [19]:
ones = np.ones((5,5))

In [20]:
ones

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [21]:
type(ones)

numpy.ndarray

In [22]:
ones.dtype

dtype('float64')

In [23]:
wal = np.arange(0,10,2)

In [24]:
wal

array([0, 2, 4, 6, 8])

In [25]:
wal.dtype

dtype('int32')

In [26]:
type(wal)

numpy.ndarray

In [27]:
np.random.seed(0)
wall = np.random.randn(4,5)
wall

array([[ 1.76405235,  0.40015721,  0.97873798,  2.2408932 ,  1.86755799],
       [-0.97727788,  0.95008842, -0.15135721, -0.10321885,  0.4105985 ],
       [ 0.14404357,  1.45427351,  0.76103773,  0.12167502,  0.44386323],
       [ 0.33367433,  1.49407907, -0.20515826,  0.3130677 , -0.85409574]])

In [28]:
np.random.seed(seed=2)
wall1 = np.random.random((5,5))
wall1

array([[0.4359949 , 0.02592623, 0.54966248, 0.43532239, 0.4203678 ],
       [0.33033482, 0.20464863, 0.61927097, 0.29965467, 0.26682728],
       [0.62113383, 0.52914209, 0.13457995, 0.51357812, 0.18443987],
       [0.78533515, 0.85397529, 0.49423684, 0.84656149, 0.07964548],
       [0.50524609, 0.0652865 , 0.42812233, 0.09653092, 0.12715997]])

## 3. Viewing arrays and matrices


In [29]:
np.unique(wall1)

array([0.02592623, 0.0652865 , 0.07964548, 0.09653092, 0.12715997,
       0.13457995, 0.18443987, 0.20464863, 0.26682728, 0.29965467,
       0.33033482, 0.4203678 , 0.42812233, 0.43532239, 0.4359949 ,
       0.49423684, 0.50524609, 0.51357812, 0.52914209, 0.54966248,
       0.61927097, 0.62113383, 0.78533515, 0.84656149, 0.85397529])

In [30]:
wall1[0]

array([0.4359949 , 0.02592623, 0.54966248, 0.43532239, 0.4203678 ])

In [31]:
rr = np.random.randint(6, size=(3,2,5,6))
rr

array([[[[4, 2, 4, 2, 1, 0],
         [2, 5, 2, 1, 5, 0],
         [1, 0, 2, 5, 1, 1],
         [1, 4, 2, 3, 0, 3],
         [0, 2, 2, 0, 4, 2]],

        [[0, 2, 4, 1, 5, 3],
         [0, 2, 1, 4, 0, 1],
         [5, 1, 5, 5, 1, 2],
         [4, 2, 3, 4, 5, 2],
         [0, 2, 3, 3, 0, 0]]],


       [[[5, 3, 5, 3, 5, 0],
         [0, 2, 5, 3, 1, 5],
         [2, 3, 4, 3, 3, 1],
         [4, 2, 3, 0, 0, 2],
         [5, 4, 4, 3, 2, 1]],

        [[1, 1, 2, 1, 3, 0],
         [1, 0, 4, 3, 1, 3],
         [0, 0, 5, 3, 2, 2],
         [5, 2, 1, 3, 5, 4],
         [3, 1, 0, 3, 0, 3]]],


       [[[1, 3, 5, 3, 0, 1],
         [4, 2, 1, 5, 1, 2],
         [0, 2, 0, 4, 3, 1],
         [5, 0, 5, 1, 5, 4],
         [2, 0, 3, 3, 2, 4]],

        [[0, 3, 0, 0, 4, 5],
         [1, 3, 3, 3, 3, 2],
         [5, 5, 2, 5, 5, 4],
         [4, 1, 4, 5, 0, 5],
         [4, 0, 2, 3, 5, 1]]]])

In [32]:
np.unique(rr)

array([0, 1, 2, 3, 4, 5])

In [33]:
rr[:,:,4,:2]

array([[[0, 2],
        [0, 2]],

       [[5, 4],
        [3, 1]],

       [[2, 0],
        [4, 0]]])

In [34]:
a1

array([1, 2, 3])

In [35]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6. ]])

In [36]:
a1 + a2

array([[2. , 4. , 6.3],
       [5. , 7. , 9. ]])

In [37]:
a1 * a2

array([[ 1. ,  4. ,  9.9],
       [ 4. , 10. , 18. ]])

In [38]:
a2 * a3

ValueError: operands could not be broadcast together with shapes (2,3) (1,3,3) 

In [39]:
a22 = a2.reshape(1,3,2)

In [40]:
a22

array([[[1. , 2. ],
        [3.3, 4. ],
        [5. , 6. ]]])

In [41]:
a22* a3

ValueError: operands could not be broadcast together with shapes (1,3,2) (1,3,3) 

In [42]:
a22.shape

(1, 3, 2)

In [43]:
a3.shape

(1, 3, 3)

In [44]:
4//3

1

In [45]:
5//2

2

In [46]:
7/4

1.75

In [47]:
7//4

1

In [48]:
a1

array([1, 2, 3])

In [49]:
sum(a1)

6

In [50]:
np.sum(a1)

6

In [51]:
perp = np.random.random(100000)

In [52]:
perp

array([0.05148819, 0.62327234, 0.28626925, ..., 0.0873402 , 0.5927684 ,
       0.12349547])

In [53]:
perp[:10]

array([0.05148819, 0.62327234, 0.28626925, 0.81278195, 0.54587271,
       0.01827003, 0.01611026, 0.93503573, 0.39058568, 0.91065551])

In [54]:
%timeit sum(perp) #Timing the numpy sum on perp
%timeit np.sum(perp)

19.1 ms ± 752 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)
60.6 µs ± 11.5 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)


In [55]:
np.mean(perp)

0.4997668481926558

In [56]:
sum(perp)/len(perp)

0.4997668481926681

In [57]:
np.var(perp)

0.08375105121512494

In [58]:
np.std(perp)

0.2893977387871663

In [59]:
np.sqrt(np.var(perp))

0.2893977387871663

In [60]:
a1

array([1, 2, 3])

In [62]:
a11

NameError: name 'a11' is not defined

In [63]:
a3.shape

(1, 3, 3)

In [64]:
a2.shape

(2, 3)

In [65]:
a2*a3

ValueError: operands could not be broadcast together with shapes (2,3) (1,3,3) 

In [71]:
aa = a2.reshape(2,3,1)
aa

array([[[1. ],
        [2. ],
        [3.3]],

       [[4. ],
        [5. ],
        [6. ]]])

In [72]:
aa*a3

array([[[ 3.  ,  5.  ,  6.6 ],
        [10.  , 14.  , 17.8 ],
        [29.7 ,  6.6 , 26.07]],

       [[12.  , 20.  , 26.4 ],
        [25.  , 35.  , 44.5 ],
        [54.  , 12.  , 47.4 ]]])

In [73]:
aa.shape

(2, 3, 1)

In [74]:
a3.shape

(1, 3, 3)

In [75]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6. ]])

In [76]:
a2.T

array([[1. , 4. ],
       [2. , 5. ],
       [3.3, 6. ]])

In [77]:
a2*a2.T

ValueError: operands could not be broadcast together with shapes (2,3) (3,2) 

In [78]:
a2.T.shape

(3, 2)

In [86]:
np.random.seed(1)
num1 = np.random.randint(15, size=(3,5))
num2 = np.random.randint(15, size=(5,3))

In [87]:
num1.shape
num2.shape

(5, 3)

In [88]:
num1

array([[ 5, 11, 12,  8,  9],
       [11,  5,  0,  0,  1],
       [12,  7, 13, 12,  6]])

In [89]:
num2

array([[ 9,  2,  4],
       [14,  5,  2],
       [ 4, 11, 12],
       [10, 12, 13],
       [14,  2,  4]])

In [90]:
num1*num2

ValueError: operands could not be broadcast together with shapes (3,5) (5,3) 

np.dot(num1, num2)

In [91]:
np.dot(num1, num2)

array([[453, 311, 326],
       [183,  49,  58],
       [462, 358, 398]])

In [92]:
np.dot(num2, num1)

array([[115, 137, 160, 120, 107],
       [149, 193, 194, 136, 143],
       [285, 183, 204, 176, 119],
       [338, 261, 289, 236, 180],
       [140, 192, 220, 160, 152]])

## Sample Exercise

In [1]:
import numpy as np
import pandas as pd

In [6]:
np.random.seed(0)
sales_amount = np.random.randint(21, size=(5,3))
sales_amount

array([[12, 15,  0],
       [ 3,  3,  7],
       [ 9, 19, 18],
       [ 4,  6, 12],
       [ 1,  6,  7]])

In [9]:
weekly_sales = pd.DataFrame(sales_amount,
                           index= ["Mon", "Tues", "Wed", "Thurs", "Fri"],
                           columns = ["Almond butter", "Peanut butter", "Cashew butter"])
weekly_sales

Almond butter  Peanut butter  Cashew butter
Mon               12             15              0
Tues               3              3              7
Wed                9             19             18
Thurs              4              6             12
Fri                1              6              7

In [10]:
# Create teh prices
prices = np.array([10, 8, 12])
prices

array([10,  8, 12])

In [12]:
prices.shape

(3,)

In [13]:
butter_prices = pd.DataFrame(prices.reshape(1,3), 
                            index=["Prices"],
                            columns=["Almond butter", "Peanut butter", "Cashew butter"])
butter_prices

Almond butter  Peanut butter  Cashew butter
Prices             10              8             12

In [21]:
total_sales = (prices).dot(sales_amount.T)
total_sales

array([240, 138, 458, 232, 142])

In [24]:
butter_prices.shape,weekly_sales.shape

((1, 3), (5, 3))

In [30]:
daily_sales = butter_prices.dot(weekly_sales.T)

In [31]:
daily_sales

Mon  Tues  Wed  Thurs  Fri
Prices  240   138  458    232  142

In [26]:
weekly_sales

Almond butter  Peanut butter  Cashew butter
Mon               12             15              0
Tues               3              3              7
Wed                9             19             18
Thurs              4              6             12
Fri                1              6              7

In [39]:
weekly_sales["Total"] = daily_sales.T

In [40]:
weekly_sales

Almond butter  Peanut butter  Cashew butter  Total
Mon               12             15              0    240
Tues               3              3              7    138
Wed                9             19             18    458
Thurs              4              6             12    232
Fri                1              6              7    142

In [41]:
# Another excercise

In [45]:
np.random.seed(100)
num_of_dev = np.random.randint(100, size=(4,4))

In [47]:
amount = np.array([300, 450, 90, 85])

In [51]:
num_of_dev,

(array([[ 8, 24, 67, 87],
        [79, 48, 10, 94],
        [52, 98, 53, 66],
        [98, 14, 34, 24]]),)

In [52]:
amount

array([300, 450,  90,  85])

In [54]:
dev_table = pd.DataFrame(num_of_dev,
                        index = ["Q1","Q2","Q3","Q4"],
                        columns=["Samsung", "Apple","Tecno","Infinix"])
dev_table

Samsung  Apple  Tecno  Infinix
Q1        8     24     67       87
Q2       79     48     10       94
Q3       52     98     53       66
Q4       98     14     34       24

In [56]:
amount.shape

(4,)

In [62]:
amount_table = pd.DataFrame(amount.reshape(1,4),
                           index=["Prices"],
                           columns=["Samsung", "Apple","Tecno","Infinix"])
amount_table

Samsung  Apple  Tecno  Infinix
Prices      300    450     90       85

In [63]:
total_amount = num_of_dev.dot(amount)

In [64]:
total_amount

array([26625, 54190, 70080, 40800])

In [65]:
num_of_dev

array([[ 8, 24, 67, 87],
       [79, 48, 10, 94],
       [52, 98, 53, 66],
       [98, 14, 34, 24]])

In [68]:
dev_table["Total Quarter"] =total_amount
dev_table

Samsung  Apple  Tecno  Infinix  Total Quarter
Q1        8     24     67       87          26625
Q2       79     48     10       94          54190
Q3       52     98     53       66          70080
Q4       98     14     34       24          40800

In [69]:
dev_table

Samsung  Apple  Tecno  Infinix  Total Quarter
Q1        8     24     67       87          26625
Q2       79     48     10       94          54190
Q3       52     98     53       66          70080
Q4       98     14     34       24          40800

In [81]:
dev_table.loc[["Q1","Q2"],["Apple", "Samsung"]]

Apple  Samsung
Q1     24        8
Q2     48       79

In [82]:
dev_table.sum(axis=0)

Samsung             237
Apple               184
Tecno               164
Infinix             271
Total Quarter    191695
dtype: int64

In [83]:
num_of_dev

array([[ 8, 24, 67, 87],
       [79, 48, 10, 94],
       [52, 98, 53, 66],
       [98, 14, 34, 24]])

In [89]:
np.sort(num_of_dev)

array([[ 8, 24, 67, 87],
       [10, 48, 79, 94],
       [52, 53, 66, 98],
       [14, 24, 34, 98]])

In [90]:
np.argsort(num_of_dev)

array([[0, 1, 2, 3],
       [0, 1, 2, 3],
       [0, 1, 2, 3],
       [0, 1, 2, 3]], dtype=int64)

In [91]:
num_of_dev

array([[ 8, 24, 67, 87],
       [10, 48, 79, 94],
       [52, 53, 66, 98],
       [14, 24, 34, 98]])

## Practical Example - Turning images to number

![]ml-framework.png

![]"ml-framework.png"